### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "email@email.com",
    "password": "tricolor"
}


### User login
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "email@email.com",
    "password": "tricolor"
}


### Find user by id
GET http://localhost:3000/auth/4


### Find user by email
GET http://localhost:3000/auth?email=xxx@email.com


### Update user
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "password": "oloko"
}


### Remove user
DELETE  http://localhost:3000/auth/17
