### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "vamo@vamo.com",
    "password": "12345"
}


### User login
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "test@test.com",
    "password": "12345"
}


### User logout
POST http://localhost:3000/auth/signout


### Find user by id
GET http://localhost:3000/auth/7


### Find user by email
GET http://localhost:3000/auth?email=xxx@email.com


### Update user
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "password": "oloko"
}


### Remove user
DELETE  http://localhost:3000/auth/17


### Show currently signed-in user
GET http://localhost:3000/auth/signedin